Added verhoeffCheckDigit validation on coordinated expressions
IHTSDO/snomed-scg-parser pull request #4
Opened 2018-12-26 13:11 UTC by SamithaS

Introduced verhoeffCheckDigit validation on coordinated expressions. 
Please review and let me know the areas that needs to be changed.

2019-01-02 14:16 UTC, kaicode requested changes
Hi @SamithaS, thank you this nice enhancement.
I've completed a code review and it looks good to me.
Could you please just replace the space indentation with tab indentation so it's in line with the rest of the project then I would be happy to merge this in 👍

2019-01-03 07:44 UTC, SamithaS commented
Thanks for your feedback. :)
I have done some formatting and if this is not align with your standards please give me the relevant formatter xml for eclipse and i will reformat based on it.

2019-01-03 08:59 UTC, kaicode approved these changes

2019-01-03 09:00 UTC, merged

2019-01-03 09:01 UTC, kaicode commented
Thank you for contributing this enhancement @SamithaS !